default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do
    params = {
      package_path: '.',
      scheme: 'eudi-lib-sdjwt-swift',
      devices: [
        'iPhone 14'
      ], 
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end
end
