default_platform(:ios)

platform :ios do
  desc "Runs unit tests"
  lane :tests do

   sh("xcodebuild -version")
   sh("xcode-select -p")
   sh("xcodebuild -showsdks || true")
   sh("xcrun simctl list runtimes")
   sh("xcrun simctl list devices available")

    params = {
      package_path: '.',
      scheme: 'eudi-lib-sdjwt-swift',
      destination: "platform=iOS Simulator,name=iPhone 17,OS=latest",
      result_bundle: true
    }

    if ENV['CI'] 
      params[:xcargs] = "-skipPackagePluginValidation"
    end

    run_tests(params)
  end

  desc "Code coverage"
  lane :code_coverage do
    
    sh("xcodebuild -version")
  sh("xcode-select -p")
  sh("xcodebuild -showsdks || true")
  sh("xcrun simctl list runtimes")
  sh("xcrun simctl list devices available")

  params = {
    package_path: ".",
    scheme: "eudi-lib-sdjwt-swift",
    destination: "platform=iOS Simulator,name=iPhone 16 Pro,OS=18.6",
    result_bundle: true
  }

  params[:xcargs] = "-skipPackagePluginValidation" if ENV["CI"]

    run_tests(params)

    xcov(
      scheme: "eudi-lib-sdjwt-swift",
      output_directory: "xcov_output",
      is_swift_package: true,
      minimum_coverage_percentage: 70.0,
      include_targets: "eudi-lib-sdjwt-swift"
    )
    if ENV['CI'] != 'true'
      sh 'open ../xcov_output/index.html'
    end
  end

  before_all do
    FileUtils.remove_dir '../xcov_output', true
  end
  
end
